### ISSUE TITLE
Data migration with fake data fails

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#58]
```
Running migrations:
  Applying api.0001_initial... OK
  Applying api.0002_data_migration... OK
  Applying api.0003_fake_data...Traceback (most recent call last):
  File "/django-webapps/manage.py", line 22, in <module>
    main()
  File "/django-webapps/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/django-webapps/api/models/data_populator.py", line 28, in run
    instance._populate()
  File "/django-webapps/api/migrations/0003_fake_data.py", line 319, in _populate
    self._make_fake_students_without_group()
  File "/django-webapps/api/migrations/0003_fake_data.py", line 293, in _make_fake_students_without_group
    self.recipes.student.make(_quantity=AMOUNT_OF_STUDENTS_WITHOUT_GROUP)
  File "lib/python3.10/site-packages/model_bakery/recipe.py", line 138, in make
    return baker.make(self._model, _using=_using, **self._mapping(_using, defaults))
  File "lib/python3.10/site-packages/model_bakery/baker.py", line 121, in make
    return [
  File "lib/python3.10/site-packages/model_bakery/baker.py", line 122, in <listcomp>
    baker.make(
  File "lib/python3.10/site-packages/model_bakery/baker.py", line 385, in make
    return self._make(**params)
  File "lib/python3.10/site-packages/model_bakery/baker.py", line 463, in _make
    instance = self.instance(
  File "lib/python3.10/site-packages/model_bakery/baker.py", line 499, in instance
    self._handle_m2m(instance)
  File "lib/python3.10/site-packages/model_bakery/baker.py", line 625, in _handle_m2m
    for value in values:
TypeError: 'function' object is not iterable
```

**Comment by lemontree210** [comment]
Forgot to copy settings :)
